name: plsDonate-Express
version: "1.0"
main: click.sattr.plsDonate.PlsDonate
api-version: "1.21"
commands:
  plsdonate:
    description: Main command for plsDonate
    aliases: [pdn]
  donate:
    description: Main donation command
softdepend: [floodgate, Geyser-Spigot, Geyser, PlaceholderAPI]
